return {
	["More Stakes"] = true,
	["M Jokers"] = true,
	["Misc."] = true,
	["Tags"] = true,
	["Challenges"] = true,
	["Spectrals"] = true,
	["Vouchers"] = true,
	["Timer Mechanics"] = true,
	["Achievements"] = true,
	["Planets"] = true,
	["Cryptid"] = { ["jimball_music"] = true, ["code_music"] = true, ["exotic_music"] = true, ["big_music"] = true },
	["Epic Jokers"] = true,
	["Antimatter Deck"] = true,
	["Misc. Jokers"] = true,
	["Code Cards"] = true,
	["Misc. Decks"] = true,
	["Exotic Jokers"] = true,
	["Enhanced Decks"] = true,
	["Blinds"] = true,
	["HTTPS Module"] = false,
	["JokerDisplay"] = true,
	["PokerHands"] = true,
	["Spooky"] = true,
	["Menu"] = true,
}
